### ISSUE TITLE
100% cpu usage of one core with docker-compose

### ISSUE THREAD

**Issue by capc0** [thegitfather/docker-debian-ike#4]
Im using this project with compose in the following way and noticed 100% cpu on one core.

```yml
version: "3"
services:
  ike-vpn:
    image: debian-ike:0.1
    command: config.vpn
    volumes:
      - ./volume:/mnt/volume
    privileged: true
    network_mode: "host"
    #restart: always
```

I adapted the scripts based on this SO thread https://askubuntu.com/questions/1022222/ikec-causes-high-cpu-usage-when-started-as-background-process

- Add `screen` to Dockerfile https://github.com/thegitfather/docker-debian-ike/blob/master/Dockerfile#L11
- use screen `screen -S "ikescreen" -d -m ikec -r "${CONFIG}" -u ${USER} -p ${PW} -a &` in startup.sh at https://github.com/thegitfather/docker-debian-ike/blob/master/startup.sh#L50
